import { fizzbuzz } from "./fizzbuzz"
import { describe } from "node:test"

const adapter = (paramètreDeTypeAny: any) =>
  typeof paramètreDeTypeAny !== "string"
    ? paramètreDeTypeAny + ""
    : paramètreDeTypeAny

describe("fizzbuzz spell checking", () => {
  test.each([
    { number: 1, expectedWord: adapter(1) },
    { number: 2, expectedWord: adapter(2) },
    { number: 3, expectedWord: "Fizz" },
    { number: 4, expectedWord: adapter(4) },
    { number: 5, expectedWord: "Buzz" },
    { number: 6, expectedWord: "Fizz" },
    { number: 7, expectedWord: adapter(7) },
    { number: 8, expectedWord: adapter(8) },
    { number: 9, expectedWord: "Fizz" },
    { number: 10, expectedWord: "Buzz" },
    { number: 11, expectedWord: adapter(11) },
    { number: 12, expectedWord: "Fizz" },
    { number: 13, expectedWord: adapter(13) },
    { number: 14, expectedWord: adapter(14) },
    { number: 15, expectedWord: "Fizz Buzz" },
    { number: 16, expectedWord: adapter(16) },
    { number: 17, expectedWord: adapter(17) },
    { number: 18, expectedWord: "Fizz" },
    { number: 19, expectedWord: adapter(19) },
    { number: 20, expectedWord: "Buzz" },
    { number: 21, expectedWord: "Fizz" },
    { number: 22, expectedWord: adapter(22) },
    { number: 23, expectedWord: adapter(23) },
    { number: 24, expectedWord: "Fizz" },
    { number: 25, expectedWord: "Buzz" },
    { number: 26, expectedWord: adapter(26) },
    { number: 27, expectedWord: "Fizz" },
    { number: 28, expectedWord: adapter(28) },
    { number: 29, expectedWord: adapter(29) },
    { number: 30, expectedWord: "Fizz Buzz" },
    { number: 31, expectedWord: adapter(31) },
    { number: 32, expectedWord: adapter(32) },
    { number: 33, expectedWord: "Fizz" },
    { number: 34, expectedWord: adapter(34) },
    { number: 35, expectedWord: "Buzz" },
    { number: 36, expectedWord: "Fizz" },
    { number: 37, expectedWord: adapter(37) },
    { number: 38, expectedWord: adapter(38) },
    { number: 39, expectedWord: "Fizz" },
    { number: 40, expectedWord: "Buzz" },
    { number: 41, expectedWord: adapter(41) },
    { number: 42, expectedWord: "Fizz" },
    { number: 43, expectedWord: adapter(43) },
    { number: 44, expectedWord: adapter(44) },
    { number: 45, expectedWord: "Fizz Buzz" },
    { number: 46, expectedWord: adapter(46) },
    { number: 47, expectedWord: adapter(47) },
    { number: 48, expectedWord: "Fizz" },
    { number: 49, expectedWord: adapter(49) },
    { number: 50, expectedWord: "Buzz" },
    { number: 51, expectedWord: "Fizz" },
    { number: 52, expectedWord: adapter(52) },
    { number: 53, expectedWord: adapter(53) },
    { number: 54, expectedWord: "Fizz" },
    { number: 55, expectedWord: "Buzz" },
    { number: 56, expectedWord: adapter(56) },
    { number: 57, expectedWord: "Fizz" },
    { number: 58, expectedWord: adapter(58) },
    { number: 59, expectedWord: adapter(59) },
    { number: 60, expectedWord: "Fizz Buzz" },
    { number: 61, expectedWord: adapter(61) },
    { number: 62, expectedWord: adapter(62) },
    { number: 63, expectedWord: "Fizz" },
    { number: 64, expectedWord: adapter(64) },
    { number: 65, expectedWord: "Buzz" },
    { number: 66, expectedWord: "Fizz" },
    { number: 67, expectedWord: adapter(67) },
    { number: 68, expectedWord: adapter(68) },
    { number: 69, expectedWord: "Fizz" },
    { number: 70, expectedWord: "Buzz" },
    { number: 71, expectedWord: adapter(71) },
    { number: 72, expectedWord: "Fizz" },
    { number: 73, expectedWord: adapter(73) },
    { number: 74, expectedWord: adapter(74) },
    { number: 75, expectedWord: "Fizz Buzz" },
    { number: 76, expectedWord: adapter(76) },
    { number: 77, expectedWord: adapter(77) },
    { number: 78, expectedWord: "Fizz" },
    { number: 79, expectedWord: adapter(79) },
    { number: 80, expectedWord: "Buzz" },
    { number: 81, expectedWord: "Fizz" },
    { number: 82, expectedWord: adapter(82) },
    { number: 83, expectedWord: adapter(83) },
    { number: 84, expectedWord: "Fizz" },
    { number: 85, expectedWord: "Buzz" },
    { number: 86, expectedWord: adapter(86) },
    { number: 87, expectedWord: "Fizz" },
    { number: 88, expectedWord: adapter(88) },
    { number: 89, expectedWord: adapter(89) },
    { number: 90, expectedWord: "Fizz Buzz" },
    { number: 91, expectedWord: adapter(91) },
    { number: 92, expectedWord: adapter(92) },
    { number: 93, expectedWord: "Fizz" },
    { number: 94, expectedWord: adapter(94) },
    { number: 95, expectedWord: "Buzz" },
    { number: 96, expectedWord: "Fizz" },
    { number: 97, expectedWord: adapter(97) },
    { number: 98, expectedWord: adapter(98) },
    { number: 99, expectedWord: "Fizz" },
    { number: 100, expectedWord: "Buzz" },
  ])(
    "$number should be spelled as $expectedWord",
    ({ number, expectedWord: spelledAsExpected }) => {
      const wordToSpell = fizzbuzz(number)

      expect(wordToSpell).toBe(spelledAsExpected)
    }
  )
})
