[package]
name = "rover"
version = "0.1.0"
authors = ["bec <benoit.chiquet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
