warn-dirty = false
extra-experimental-features = flakes nix-command
extra-trusted-substituters = https://pinage404-nix-sandboxes.cachix.org
extra-trusted-public-keys = pinage404-nix-sandboxes.cachix.org-1:5zGRK2Ou+C27E7AdlYo/s4pow/w39afir+KRz9iWsZA=
filter-syscalls = false # avoid the error "unable to load seccomp BPF program: Invalid argument" which happen on Mac ARM https://github.com/NixOS/nix/issues/5258#issuecomment-921030592
