<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>xpug.kata</groupId>
    <artifactId>birthday-greetings</artifactId>
    <version>${revision}</version>

    <properties>
        <!--versions-->
        <maven.compiler.release>${java-sources.version}</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>0.0.1-SNAPSHOT</revision>
        <java-sources.version>27</java-sources.version>
        <java-bytecode.version>27</java-bytecode.version>
        <maven.version>3.9.16</maven.version>
        <angus-mail.version>2.0.5</angus-mail.version>
        <checkstyle.version>14.3.0</checkstyle.version>
        <errorprone.version>2.50.0</errorprone.version>
        <greenmail.version>2.1.14</greenmail.version>
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>
        <jakarta-mail.version>2.0.1</jakarta-mail.version>
        <junit.version>6.1.3</junit.version>
        <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
        <maven-compiler-plugin.version>3.16.0</maven-compiler-plugin.version>
        <maven-enforcer-plugin.version>3.6.3</maven-enforcer-plugin.version>
        <maven-pmd-plugin.version>3.28.0</maven-pmd-plugin.version>
        <maven-surefire-plugin.version>3.6.0</maven-surefire-plugin.version>
        <maven-surefire-junit5-tree-reporter.version>1.5.1</maven-surefire-junit5-tree-reporter.version>
        <nullaway.version>0.13.8</nullaway.version>
        <pitest.version>1.30.0</pitest.version>
        <pitest-junit5-plugin.version>1.2.3</pitest-junit5-plugin.version>
        <pmd.version>7.28.0</pmd.version>
        <spotless-maven-plugin.version>3.10.3</spotless-maven-plugin.version>
        <tidy-maven-plugin.version>1.4.1</tidy-maven-plugin.version>
        <!--severity on build-->
        <compiler.fail-on-warns>false</compiler.fail-on-warns>
        <pmd.fail-on-warns>false</pmd.fail-on-warns>
        <!--lifecycle control-->
        <checkstyle.check.phase>none</checkstyle.check.phase>
        <jacoco.prepare-agent.phase>none</jacoco.prepare-agent.phase>
        <jacoco.report.phase>none</jacoco.report.phase>
        <jakarta.mail.version>2.0.1</jakarta.mail.version>
        <pitest.mutation-coverage.phase>none</pitest.mutation-coverage.phase>
        <pmd.check.phase>none</pmd.check.phase>
        <spotless.apply.phase>validate</spotless.apply.phase>
        <spotbugs.check.phase>none</spotbugs.check.phase>
        <tests.skip>false</tests.skip>
        <tidy.pom.phase>validate</tidy.pom.phase>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>jakarta.mail</artifactId>
            <version>${jakarta-mail.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.angus</groupId>
            <artifactId>angus-mail</artifactId>
            <version>${angus-mail.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.icegreen</groupId>
            <artifactId>greenmail</artifactId>
            <version>${greenmail.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- COMPILATION -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java-sources.version}</source>
                    <target>${java-bytecode.version}</target>
                    <release>${java-bytecode.version}</release>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>com.google.errorprone</groupId>
                                    <artifactId>error_prone_core</artifactId>
                                    <version>${errorprone.version}</version>
                                </path>
                                <path>
                                    <groupId>com.uber.nullaway</groupId>
                                    <artifactId>nullaway</artifactId>
                                    <version>${nullaway.version}</version>
                                </path>
                            </annotationProcessorPaths>
                            <failOnWarning>${compiler.fail-on-warns}</failOnWarning>
                            <compilerArgs>
                                <arg>-Xlint:all,-serial</arg>
                                <arg>-XDcompilePolicy=simple</arg>
                                <arg>--should-stop=ifError=FLOW</arg>
                                <arg>-Xplugin:ErrorProne \
                                -XepOpt:NullAway:AnnotatedPackages=acme.foo \
                                @${project.basedir}/errorprone.cfg</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- TEST -->
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <skipTests>${tests.skip}</skipTests>
                    <statelessTestsetInfoReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoTreeReporter" />
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>me.fabriciorby</groupId>
                        <artifactId>maven-surefire-junit5-tree-reporter</artifactId>
                        <version>${maven-surefire-junit5-tree-reporter.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <!-- COVERAGE -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <phase>${jacoco.prepare-agent.phase}</phase>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <phase>${jacoco.report.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <!-- MUTATION TESTING -->
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest.version}</version>
                <configuration>
                    <exportLineCoverage>true</exportLineCoverage>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>${pitest-junit5-plugin.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>mutation-coverage</id>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <phase>${pitest.mutation-coverage.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <!-- LINTING -->
            <plugin>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <configuration>
                    <configLocation>google_checks.xml</configLocation>
                    <includeResources>false</includeResources>
                    <includeTestSourceDirectory>true</includeTestSourceDirectory>
                    <sourceDirectories>
                        <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
                        <sourceDirectory>${project.build.testSourceDirectory}</sourceDirectory>
                    </sourceDirectories>
                    <suppressionsLocation>checkstyle_suppressions.xml</suppressionsLocation>
                    <violationSeverity>warning</violationSeverity>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>${checkstyle.version}</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>${checkstyle.check.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${maven-pmd-plugin.version}</version>
                <configuration>
                    <analysisCache>true</analysisCache>
                    <failOnViolation>${pmd.fail-on-warns}</failOnViolation>
                    <includeTests>true</includeTests>
                    <linkXRef>false</linkXRef>
                    <printFailingErrors>true</printFailingErrors>
                    <rulesets>
                        <ruleset>pmd_ruleset.xml</ruleset>
                    </rulesets>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>${pmd.version}</version>
                        <scope>runtime</scope>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>${pmd.version}</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                            <goal>cpd-check</goal>
                        </goals>
                        <phase>${pmd.check.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <!-- FORMAT -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>tidy-maven-plugin</artifactId>
                <version>${tidy-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>${tidy.check.phase}</phase>
                    </execution>
                    <execution>
                        <id>fix</id>
                        <goals>
                            <goal>pom</goal>
                        </goals>
                        <phase>${tidy.pom.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless-maven-plugin.version}</version>
                <configuration>
                    <java>
                        <endWithNewline />
                        <formatAnnotations />
                        <googleJavaFormat />
                        <toggleOffOn />
                    </java>
                    <pom>
                        <includes>
                            <include>checkstyle_suppressions.xml</include>
                            <include>pom.xml</include>
                            <include>pmd_ruleset.xml</include>
                        </includes>
                        <sortPom>
                            <expandEmptyElements>false</expandEmptyElements>
                            <indentAttribute />
                            <lineSeparator>\n</lineSeparator>
                            <nrOfIndentSpace>4</nrOfIndentSpace>
                            <spaceBeforeCloseEmptyElement>true</spaceBeforeCloseEmptyElement>
                        </sortPom>
                    </pom>
                </configuration>
                <executions>
                    <execution>
                        <id>check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>${spotless.check.phase}</phase>
                    </execution>
                    <execution>
                        <id>fix</id>
                        <goals>
                            <goal>apply</goal>
                        </goals>
                        <phase>${spotless.apply.phase}</phase>
                    </execution>
                </executions>
            </plugin>
            <!-- MISC -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven-enforcer-plugin.version}</version>
                <executions>
                    <execution>
                        <id>enforce-versions</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <inherited>false</inherited>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>${maven.version}</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>${java-sources.version}</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>check</id>
            <properties>
                <checkstyle.check.phase>verify</checkstyle.check.phase>
                <compiler.fail-on-warns>true</compiler.fail-on-warns>
                <pmd.check.phase>verify</pmd.check.phase>
                <pmd.fail-on-warns>true</pmd.fail-on-warns>
            </properties>
        </profile>
        <profile>
            <id>coverage</id>
            <properties>
                <jacoco.prepare-agent.phase>process-test-classes</jacoco.prepare-agent.phase>
                <jacoco.report.phase>test</jacoco.report.phase>
            </properties>
        </profile>
        <profile>
            <id>lint</id>
            <properties>
                <checkstyle.check.phase>verify</checkstyle.check.phase>
                <compiler.fail-on-warns>true</compiler.fail-on-warns>
                <pmd.check.phase>verify</pmd.check.phase>
                <pmd.fail-on-warns>true</pmd.fail-on-warns>
                <tests.skip>true</tests.skip>
            </properties>
        </profile>
        <profile>
            <id>mutations</id>
            <properties>
                <pitest.mutation-coverage.phase>process-test-classes</pitest.mutation-coverage.phase>
            </properties>
        </profile>
    </profiles>
</project>
