#!/usr/bin/env sh
set -o errexit

# uncomment this to enable git-time-keeper with only git ; without git-gamble
# if command -v git-time-keeper >/dev/null && [ -n "${TIME_KEEPER_MAXIMUM_ITERATION_DURATION+empty}" ]; then
#     git-time-keeper 'start'
# fi
