rules = [
  DisableSyntax,
  ExplicitResultTypes,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  OrganizeImports,
  ProcedureSyntax,
  RedundantSyntax,
  RemoveUnused,
  # Community rules
  ## Unified
  EmptyCollectionsUnified,
  ## Pixiv
  CheckIsEmpty,
  MockitoThenToDo,
  NamingConventionPackage,
  NeedMessageExtendsRuntimeException,
  NonCaseException,
  PackageJavaxToJakarta,
  ScalatestAssertThrowsToIntercept,
  SingleConditionMatch,
  UnnecessarySemicolon,
  UnifiedArrow,
  UnifyEmptyList,
  ZeroIndexToHead,
  ## ScapeGoat
  ArrayEquals,
  ArraysInFormat,
  ArraysToString,
  AsInstanceOf,
  AvoidSizeEqualsZero,
  AvoidSizeNotEqualsZero,
  AvoidToMinusOne,
  BigDecimalDoubleConstructor,
  BigDecimalScaleWithoutRoundingMode,
  BoundedByFinalType,
  BrokenOddness,
  CatchException,
  CatchExceptionImmediatelyRethrown,
  CatchFatal,
  CatchNpe,
  CatchThrowable,
  ClassNames,
  CollectionIndexOnNonIndexedSeq,
  CollectionNamingConfusion,
  CollectionNegativeIndex,
  CollectionPromotionToAny,
  ComparisonToEmptyList,
  ComparisonToEmptySet,
  ComparisonWithSelf,
  ConstantIf,
  DivideByOne,
  DoubleNegation,
  DuplicateImport,
  DuplicateMapKey,
  DuplicateSetValue,
  EitherGet,
  EmptyCaseClass,
  EmptyFor,
  EmptyIfBlock,
  EmptyInterpolatedString,
  EmptyMethod,
  EmptySynchronizedBlock,
  EmptyTryBlock,
  EmptyWhileBlock,
  ExistsSimplifiableToContains,
  FilterDotHead,
  FilterDotHeadOption,
  FilterDotIsEmpty,
  FilterDotSize,
  FilterOptionAndGet,
  # FinalModifierOnCaseClass,
  FinalizerWithoutSuper,
  FindAndNotEqualsNoneReplaceWithExists,
  FindDotIsDefined,
  IllegalFormatString,
  ImpossibleOptionSizeCondition,
  IncorrectNumberOfArgsToFormat,
  IncorrectlyNamedExceptions,
  InvalidRegexTest,
  IsInstanceOf,
  InterpolationToString,
  LonelySealedTrait,
  LooksLikeInterpolatedString,
  MapGetAndGetOrElse,
  MethodReturningAny,
  NanComparison,
  NullAssignment,
  NullParameter,
  OptionGet,
  OptionSize,
  RepeatedCaseBody,
  RepeatedIfElseBody,
  StripMarginOnRegex,
  SwallowedException,
  TryGet,
  UnnecessaryConversion,
  UnreachableCatch,
  UnsafeContains,
  UnsafeStringContains,
  UnsafeTraversableMethods,
  UnusedMethodParameter,
  VarCouldBeVal,
  VariableShadowing,
  WhileTrue,
]

DisableSyntax {
  noVars = false
  noThrows = true
  noNulls = true
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = true
  noIsInstanceOf = true
  noXml = true
  noDefaultArgs = false
  noFinalVal = true
  noFinalize = true
  noValPatterns = true
  noUniversalEquality = false
  regex = []
}

ExplicitResultTypes {
  memberKind = [Def]
  memberVisibility = [Public, Private, Protected]
  skipSimpleDefinitions = false
  fatalWarnings = true
  rewriteStructuralTypesToNamedSubClass = false
  onlyImplicits = false
  fetchScala3CompilerArtifactsOnVersionMismatch = false
}

OrganizeImports {
  blankLines = Auto
  coalesceToWildcardImportThreshold = null
  expandRelative = true
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = AggressiveMerge
  groups = ["*", "re:(javax?|scala)\\."]
  importSelectorsOrder = SymbolsFirst
  importsOrder = SymbolsFirst
  # preset = DEFAULT
  removeUnused = true
  targetDialect = Scala3
}

RedundantSyntax {
  finalObject = true
  stringInterpolator = true
}

RemoveUnused {
  imports = true
  privates = true
  locals = true
  patternvars = true
  params = true
}
